
version: '3.7'
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3307:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
      PMA_PORT: 3306